services:
  backend_app:
    container_name: backend_app
    build: .
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://192.168.94.33:5432/sundaram  # Ensure PostgreSQL is listening on 0.0.0.0
      DATABASE_USER: postgres
      DATABASE_PASSWORD: rohith
    ports:
      - "192.168.94.33:8081:8081"
    networks:
      - app_network

networks:
  app_network:
