#sonar.projectKey=SpringBootProject
#sonar.projectName=SpringBootProject
sonar.projectKey=ForexCard1
sonar.projectName=ForexCard1
sonar.login=admin
sonar.password=1234
sonar.projectVersion=1.0
sonar.sources=C:/Users/admin/Downloads/backend-final/ForexCard/src
sonar.language=java
sonar.exclusions=**/*.class
sonar.java.binaries=C:/Users/admin/Downloads/backend-final/ForexCard/src
